#!/usr/bin/env php
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require dirname(__FILE__) . '/PHPMailer/src/Exception.php';
require dirname(__FILE__) . '/PHPMailer/src/PHPMailer.php';
require dirname(__FILE__) . '/PHPMailer/src/SMTP.php';

/* Arguments containing Nagios Alert/Notification Info */
array_shift($argv);
$CONTACTEMAIL  =array_shift($argv);           /*10*/
$NOTIFICATIONTYPE =array_shift($argv);  /*1*/
$HOSTNAME =array_shift($argv);    /*2*/
$HOSTALIAS =array_shift($argv);    /*2*/
$HOSTADDRESS =array_shift($argv);   /*5*/
$LONGDATETIME =array_shift($argv);     /*7*/
$NOTIFICATIONAUTHOR= array_shift($argv);     /*20*/
$NOTIFICATIONCOMMENT= array_shift($argv);     /*21*/
$NOTIFICATIONISESCALATED= array_shift($argv);     /*23*/
$NOTIFICATIONRECIPIENTS= array_shift($argv);  /*26*/
$OUTPUT =array_shift($argv);   /*6*/
$DURATION= array_shift($argv);     /*22*/
$STATE  =array_shift($argv);   /*9*/
$SERVICEDESC  =array_shift($argv);    /*8*/


switch ($NOTIFICATIONTYPE) {
case 'PROBLEM':
	if($STATE=="WARNING") {
		$f_color="#FFBF00";
		$NOTIFICATIONAUTHOR_desc="Acknowledged Author:";
		$NOTIFICATIONCOMMENT_desc="Acknowledged Comment:";
	} else{		
		$f_color="#FF0000";
		$NOTIFICATIONAUTHOR_desc="Acknowledged Author:";
		$NOTIFICATIONCOMMENT_desc="Acknowledged Comment:";
	}
	break;
case 'RECOVERY':
	$f_color="#00FF00";
	$NOTIFICATIONAUTHOR_desc="Acknowledged Author:";
	$NOTIFICATIONCOMMENT_desc="Acknowledged Comment:";
	break;
case 'ACKNOWLEDGEMENT':
	$f_color="#AEB6BF";
	$NOTIFICATIONAUTHOR_desc="Acknowledged Author:";
	$NOTIFICATIONCOMMENT_desc="Acknowledged Comment:";
	break;
case 'FLAPPINGSTART':
	$f_color="#800000";
	$NOTIFICATIONAUTHOR_desc="Flapping Author:";
	$NOTIFICATIONCOMMENT_desc="Flapping Comment:";
	break;
case 'FLAPPINGSTOP':
	$f_color="#008000";
	$NOTIFICATIONAUTHOR_desc="Flapping Author:";
	$NOTIFICATIONCOMMENT_desc="Flapping Comment:";
	break;
case 'FLAPPINGDISABLED':
	$f_color="#F7FE2E";
	$NOTIFICATIONAUTHOR_desc="Flapping Author:";
	$NOTIFICATIONCOMMENT_desc="Flapping Comment:";
	break;
case 'DOWNTIMESTART':
	$f_color="#5DADE2";
	$NOTIFICATIONAUTHOR_desc="Scheduled Downtime by:";
	$NOTIFICATIONCOMMENT_desc="Comment for Scheduled Downtime:";
	break;
case 'DOWNTIMEEND':
	$f_color="#48C9B0";
	$NOTIFICATIONAUTHOR_desc="Scheduled Downtime by:";
	$NOTIFICATIONCOMMENT_desc="Comment for Scheduled Downtime:";
	break;
case 'DOWNTIMECANCELLED':
	$f_color="#AF7AC5";
	$NOTIFICATIONAUTHOR_desc="Scheduled Downtime by:";
	$NOTIFICATIONCOMMENT_desc="Comment for Scheduled Downtime:";
	break;
case 'CUSTOM':
	$f_color="#5D6D7E";
	$NOTIFICATIONAUTHOR_desc="Custom Author:";
	$NOTIFICATIONCOMMENT_desc="Custom Comment:";
	break;
default:
	$f_color="#5D6D7E";
	$NOTIFICATIONAUTHOR_desc="Acknowledged Author:";
	$NOTIFICATIONCOMMENT_desc="Acknowledged Comment:";
	break;
}

/* Check if acknowledgement is present and if so, then add HTML code */
if($NOTIFICATIONAUTHOR!="" && $NOTIFICATIONCOMMENT!=""){
	$NOTIFICATIONAUTHOR_status = '
		<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">' . $NOTIFICATIONAUTHOR_desc . '</h4>
		<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $NOTIFICATIONAUTHOR . '</h2>
		';

	$NOTIFICATIONCOMMENT_status = '
		<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">' . $NOTIFICATIONCOMMENT_desc . '</h4>
		<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $NOTIFICATIONCOMMENT . '</h2>
		';

	$NOTIFICATIONAUTHOR_status_none_html = $NOTIFICATIONAUTHOR_desc . ' ' . $NOTIFICATIONAUTHOR;

	$NOTIFICATIONCOMMENT_status_none_html = $NOTIFICATIONCOMMENT_desc . ' ' . $NOTIFICATIONCOMMENT;
} else{
	$NOTIFICATIONAUTHOR_status = '';
	$NOTIFICATIONCOMMENT_status = '';
	$NOTIFICATIONAUTHOR_status_none_html = '';
	$NOTIFICATIONCOMMENT_status_none_html = '';

}

/* Check if acknowledgement is present and if so, then add HTML code */
if($NOTIFICATIONISESCALATED==0){
	$NOTIFICATIONISESCALATED_status = '
		<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Incident Escalated:</h4>
		<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">No</h2>
		';

	$NOTIFICATIONISESCALATED_status_none_html = 'Incident Escalated: No';
}

if($NOTIFICATIONISESCALATED==1){
	$NOTIFICATIONISESCALATED_status = '
		<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Incident Escalated:</h4>
		<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">Yes</h2>
		';

	$NOTIFICATIONISESCALATED_status_none_html = 'Incident Escalated: Yes';
}

if (is_null($SERVICEDESC)) {
	$subject = "$NOTIFICATIONTYPE Host Alert: $HOSTNAME is $STATE";
	$message = "
***** Nagios *****

Notification Type: $NOTIFICATIONTYPE

Host: $HOSTNAME
Hostalias: $HOSTALIAS
State: $STATE
Address: $HOSTADDRESS

Info: $OUTPUT

Date/Time: $LONGDATETIME

$NOTIFICATIONISESCALATED_status_none_html
$NOTIFICATIONAUTHOR_status_none_html
$NOTIFICATIONCOMMENT_status_none_html
";
} else {
	$subject = "$NOTIFICATIONTYPE Service Alert: $HOSTNAME/$SERVICEDESC is $STATE";
	$message = "
***** Nagios *****

Notification Type: $NOTIFICATIONTYPE

Service: $SERVICEDESC
Host: $HOSTNAME
Hostalias: $HOSTALIAS
Address: $HOSTADDRESS
State: $STATE

Date/Time: $LONGDATETIME

Additional Info:

$OUTPUT

$NOTIFICATIONISESCALATED_status_none_html
$NOTIFICATIONAUTHOR_status_none_html
$NOTIFICATIONCOMMENT_status_none_html
";
}

$OUTPUT = str_replace('\n', '<br />',$OUTPUT);

/* HTML EMAIL CONTENT */
$HTMLmessage = '

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="description" content="Nagios Email Notification Alert">
<meta name="viewport" content="width=device-width">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="x-apple-disable-message-reformatting">
<title>' . $subject . '</title>

<!--[if mso]>
<style>
* {
	font-family: sans-serif !important;
}
</style>
<![endif]-->

<!--[if !mso]><!-->
<link href="https://font.internet.fo/stylesheet.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<!--<![endif]-->

<style>

html,
	body {
margin: 0 auto !important;
padding: 0 !important;
height: 100% !important;
width: 100% !important;
	}

* {
	-ms-text-size-adjust: 100%;
	-webkit-text-size-adjust: 100%;
}

div[style*="margin: 16px 0"] {
margin:0 !important;
}

table,
	td {
		mso-table-lspace: 0pt !important;
		mso-table-rspace: 0pt !important;
	}

table {
	border-spacing: 0 !important;
	border-collapse: collapse !important;
	table-layout: fixed !important;
margin: 0 auto !important;
}
table table table {
	table-layout: auto;
}

img {
	-ms-interpolation-mode:bicubic;
}

*[x-apple-data-detectors],	/* iOS */
	.x-gmail-data-detectors, 	/* Gmail */
	.x-gmail-data-detectors *,
	.aBn {
		border-bottom: 0 !important;
cursor: default !important;
color: inherit !important;
       text-decoration: none !important;
       font-size: inherit !important;
       font-family: inherit !important;
       font-weight: inherit !important;
       line-height: inherit !important;
	}

.a6S {
display: none !important;
opacity: 0.01 !important;
}
img.g-img + div {
display:none !important;
}

.button-link {
	text-decoration: none !important;
}

@media only screen and (min-device-width: 375px) and (max-device-width: 413px) { /* iPhone 6 and 6+ */
	.email-container {
		min-width: 375px !important;
	}
}

</style>

<style>

.button-td,
	.button-a {
transition: all 100ms ease-in;
	}
.button-td:hover,
	.button-a:hover {
background: #555555 !important;
	    border-color: #555555 !important;
	}

@media screen and (max-width: 600px) {

	.email-container p {
		font-size: 17px !important;
		line-height: 22px !important;
	}

}

</style>

<!--[if gte mso 9]>
<xml>
<o:OfficeDocumentSettings>
<o:AllowPNG/>
<o:PixelsPerInch>96</o:PixelsPerInch>
</o:OfficeDocumentSettings>
</xml>
<![endif]-->

</head>
<body width="100%" bgcolor="#f6f6f6" style="margin: 0;line-height:1.4;padding:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;">
<center style="width: 100%; background: #f6f6f6; text-align: left;">

<div style="display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all;font-family: sans-serif;">';

if (is_null($SERVICEDESC)) {
	$HTMLmessage .= '[' .$NOTIFICATIONTYPE. '] Host: ' .$HOSTNAME . ' is ' .$STATE; 
} else {
	$HTMLmessage .= '[' .$NOTIFICATIONTYPE. '] Service: ' .$SERVICEDESC. ' on Host: ' .$HOSTNAME. ' is ' .$STATE; 

}

$HTMLmessage .= '
. ***************************************************************************************************************************************
	</div>

	<div style="max-width: 600px; padding: 10px 0; margin: auto;" class="email-container">
	<!--[if mso]>
	<table role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" align="center">
	<tr>
	<td>
	<![endif]-->

	<table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="95%" style="max-width: 600px;">
	<tr>
	<td bgcolor="#ffffff" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;-webkit-border-top-right-radius: 25px;-webkit-border-top-left-radius: 25px;-moz-border-top-right-radius: 25px;-moz-border-top-left-radius: 25px;border-top-right-radius: 25px;border-top-left-radius: 25px;-webkit-border-bottom-right-radius: 25px;-webkit-border-bottom-left-radius: 25px;-moz-border-bottom-right-radius: 25px;-moz-border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;border-bottom-left-radius: 25px;">
	<table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" align="center" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;-webkit-border-top-right-radius: 25px;-webkit-border-top-left-radius: 25px;-moz-border-top-right-radius: 25px;-moz-border-top-left-radius: 25px;border-top-right-radius: 25px;border-top-left-radius: 25px;">
	<tbody>
	<tr>
	<td style="background-color:#424242;-webkit-border-top-right-radius: 25px;-webkit-border-top-left-radius: 25px;-moz-border-top-right-radius: 25px;-moz-border-top-left-radius: 25px;border-top-right-radius: 25px;border-top-left-radius: 25px;">
	<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#ffffff; text-align:center;">Alert Notification</h2>
	</td>
	</tr>
	<tr>
	<td style="background-color:' .$f_color. ';">
	<h1 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; padding:0; margin:10px; color:#ffffff; text-align:center;">' .$NOTIFICATIONTYPE. '</h1>
	</td>
	</tr>
	</tbody>
	</table>
	<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;border-left-style: solid;border-right-style: solid;border-color: #d3d3d3;border-width: 1px;">
	<td style="font-size:16px;vertical-align:top;">&nbsp;</td>
	<tbody>
	<tr>
	<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
	<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; text-align:center; text-decoration:underline;">Host:</h4>
	<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:26px; text-align:center;">' . $HOSTNAME . '</h2>';
if (!is_null($SERVICEDESC)) {
	$HTMLmessage .= '
<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; text-align:center; text-decoration:underline;">Service:</h4>
<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:26px; text-align:center;">' . $SERVICEDESC . '</h2>';
}

$HTMLmessage .= '
<h5 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#b0b0b0; text-align:center;">is</h5>
<h1 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:30px; color:' .$f_color. ';text-align:center;">' . $STATE . '</h1>
<h5 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#b0b0b0; text-align:center;">for: ' . $DURATION . '</h5>
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%; text-decoration:underline;">Hostalias:</h4>
<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $HOSTALIAS . '</h2>
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Host Address:</h4>
<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $HOSTADDRESS . '</h2>
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Last Check:</h4>
<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $LONGDATETIME . '</h2>
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Status Information:</h4>
<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' .$OUTPUT. '</h2>
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
<h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Notified Recipients:</h4>
<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $NOTIFICATIONRECIPIENTS . '</h2>
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
' . $NOTIFICATIONISESCALATED_status . '
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
' . $NOTIFICATIONAUTHOR_status . '
</td>
</tr>
</tbody>
<td style="font-size:9px;vertical-align:top;">&nbsp;</td>
<tbody>
<tr>
<td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
' . $NOTIFICATIONCOMMENT_status . '
</td>
</tr>
</tbody>
<td style="font-size:16px;vertical-align:top;">&nbsp;</td>
</table>
<table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;-webkit-border-bottom-right-radius: 25px;-webkit-border-bottom-left-radius: 25px;-moz-border-bottom-right-radius: 25px;-moz-border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;border-bottom-left-radius: 25px;">
<tbody>
<tr>
<td style="background-color:' .$f_color. ';">
<h1 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; padding:0; margin:10px; color:#ffffff; text-align:center;">' .$NOTIFICATIONTYPE. '</h1>
</td>
</tr>
<tr>
<td style="background-color:#424242;-webkit-border-bottom-right-radius: 25px;-webkit-border-bottom-left-radius: 25px;-moz-border-bottom-right-radius: 25px;-moz-border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;border-bottom-left-radius: 25px;">
<h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#ffffff; text-align:center;">Alert Notification</h2>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</table>
<!--[if mso]>
</td>
</tr>
</table>
<![endif]-->
</div>

</center>
</body>
</html>
';
try{
	$mail = new PHPMailer(true);
	//$mail->SMTPDebug = 3; // Enable verbose debug output
	$mail->isSMTP(); // Set mailer to use SMTP
	$mail->Host = 'localhost';	// Specify main and backup SMTP servers
	$mail->SMTPAuth = false; // Enable SMTP authentication
	$mail->Port = 25;
        $mail->SMTPAutoTLS = false;

	$mail->From = 'nagios@belew.tech';
	$mail->FromName = 'Nagios';
	$mail->addAddress($CONTACTEMAIL); // Add a recipient + Name is optional "$mail->addAddress('joe@example.net', 'Joe User');"
	$mail->isHTML(true); // Set email format to HTML
	$mail->WordWrap = 50; // Set word wrap to 50 characters

	$mail->Subject = '** '.$subject.' **';
	$mail->AltBody = $message;
	$mail->Body = $HTMLmessage;
	$mail->send();
	echo 'Message has been sent<br>';
}catch(Exception $e) {
	echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}

?>
